# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
image: maven:3.6.3-jdk-11
tasks:
    - name: Install JDK 17
      init: |
        curl -s "https://get.sdkman.io" | bash
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sdk install java 17.0.8-tem
    - name: Script Task
      init: |
        mvn dependency:resolve
        mvn test-compile
        cd gitpod
      command: |
        $MVN_COMMAND