name: iOS Real Devices

on:
  schedule:
    - cron: '35 20 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**/appium/**'
      - 'pom.*'
  pull_request:
    paths:
      - '**/appium/**'
      - 'pom.*'

env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v7
      - name: Set up Java
        uses: actions/setup-java@v6
        with:
          java-version: 25
          distribution: "temurin"
      - name: RDC Native App IOS
        timeout-minutes: 30
        run: cd ./appium/appium-app/appium-app-examples && mvn test -Dtest=IOSNativeAppTest -Dregion=eu -Dsurefire.rerunFailingTestsCount=2
