name: Best Practices Tests

on:
  schedule:
    - cron: '35 22 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**/best-practice/**'
      - 'pom.*'
  pull_request:
    paths:
      - '**/best-practice/**'
      - 'pom.*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v7
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: "temurin"
      - name: Run tests
        continue-on-error: true
        uses: nick-fields/retry@v4
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: cd ./best-practice && mvn test
