name: RDC Android Native App

on:
  - push
  - pull_request

env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: RDC Native App Android
      run: mvn test -pl appium-examples -Dtest=AndroidNativeAppTest#shouldOpenApp -X
    - name: RDC Native App Android Dynamic test name
      run: |
        export ANDROID_APP=https://github.com/saucelabs/sample-app-mobile/releases/download/2.7.1/Android.SauceLabs.Mobile.Sample.app.2.7.1.apk
        mvn test -pl appium-examples -Dtest=AndroidNativeAppTest#setAppNameDynamically -X
