name: Selenium JUnit 4 Tests

on:
  schedule:
    - cron: '35 23 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**/selenium-junit4-examples/**'
      - 'pom.*'
  pull_request:
    paths:
      - '**/selenium-junit4-examples/**'
      - 'pom.*'


jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          files: "selenium-junit4-examples/**/*.java"
          skip-commit: true
      - name: Print diffs
        if: success() || failure()
        run: git --no-pager diff --exit-code

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: "temurin"
      - name: Run JUnit 4 Tests
        working-directory: ./selenium-junit4-examples
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: mvn test
